version: "3.7"

services:
  app_proxy:
    environment:
      PROXY_AUTH_ADD: "false"
      APP_HOST: $APP_SPARKKIOSK_IP
      APP_PORT: 21214

  web:
    image: habibitcoin/sparkkiosk:v1.0.1@sha256:3d9be559d3cf6ef7f53e59d6f18516a5e8b1c789cd1c52508009a301945d8526
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      # Global
   

      # LND
      LND_GRPC_ENDPOINT: $APP_LIGHTNING_NODE_IP
      LND_GRPC_PORT: $APP_LIGHTNING_NODE_GRPC_PORT
      LND_GRPC_CERT: "/lnd/tls.cert"
      LND_GRPC_MACAROON: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"

      # App
      APP_HIDDEN_SERVICE: http://$APP_HIDDEN_SERVICE
      APP_PASSWORD: $APP_PASSWORD
      APP_DOMAIN: $APP_DOMAIN
    networks:
      default:
        ipv4_address: $APP_SPARKKIOSK_IP
